#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x51722B08FE4745A2 (simon@josefsson.org)
#
Name     : oath-toolkit
Version  : 2.6.5
Release  : 5
URL      : https://download.savannah.nongnu.org/releases/oath-toolkit/oath-toolkit-2.6.5.tar.gz
Source0  : https://download.savannah.nongnu.org/releases/oath-toolkit/oath-toolkit-2.6.5.tar.gz
Source1  : https://download.savannah.nongnu.org/releases/oath-toolkit/oath-toolkit-2.6.5.tar.gz.sig
Summary  : Library for Open AuTHentication (OATH) HOTP etc support.
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+ LGPL-2.1 LGPL-2.1+
Requires: oath-toolkit-bin = %{version}-%{release}
Requires: oath-toolkit-data = %{version}-%{release}
Requires: oath-toolkit-lib = %{version}-%{release}
Requires: oath-toolkit-license = %{version}-%{release}
Requires: oath-toolkit-man = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : bison
BuildRequires : docbook-xml
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : valgrind
BuildRequires : xmlsec1-dev
BuildRequires : xz-dev

%description
The OATH Toolkit makes it easy to build one-time password
authentication systems.  It contains shared libraries, command line
tools and a PAM module.  Supported technologies include the
event-based HOTP algorithm (RFC4226) and the time-based TOTP algorithm
(RFC6238).  OATH stands for Open AuTHentication, which is the
organization that specify the algorithms.  For managing secret key
files, the Portable Symmetric Key Container (PSKC) format described in
RFC6030 is supported.

%package bin
Summary: bin components for the oath-toolkit package.
Group: Binaries
Requires: oath-toolkit-data = %{version}-%{release}
Requires: oath-toolkit-license = %{version}-%{release}

%description bin
bin components for the oath-toolkit package.


%package data
Summary: data components for the oath-toolkit package.
Group: Data

%description data
data components for the oath-toolkit package.


%package dev
Summary: dev components for the oath-toolkit package.
Group: Development
Requires: oath-toolkit-lib = %{version}-%{release}
Requires: oath-toolkit-bin = %{version}-%{release}
Requires: oath-toolkit-data = %{version}-%{release}
Provides: oath-toolkit-devel = %{version}-%{release}
Requires: oath-toolkit = %{version}-%{release}

%description dev
dev components for the oath-toolkit package.


%package doc
Summary: doc components for the oath-toolkit package.
Group: Documentation
Requires: oath-toolkit-man = %{version}-%{release}

%description doc
doc components for the oath-toolkit package.


%package lib
Summary: lib components for the oath-toolkit package.
Group: Libraries
Requires: oath-toolkit-data = %{version}-%{release}
Requires: oath-toolkit-license = %{version}-%{release}

%description lib
lib components for the oath-toolkit package.


%package license
Summary: license components for the oath-toolkit package.
Group: Default

%description license
license components for the oath-toolkit package.


%package man
Summary: man components for the oath-toolkit package.
Group: Default

%description man
man components for the oath-toolkit package.


%prep
%setup -q -n oath-toolkit-2.6.5
cd %{_builddir}/oath-toolkit-2.6.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1609362541
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
# Set custom no_proxy value for libxml2 to skip proxy scans. Otherwise, libxml2
# returns an "Unknown IO error", leading to test output mismatches.
# Reference: https://gitlab.gnome.org/GNOME/libxml2/-/blob/79301d3d5e/nanoftp.c#L196
no_proxy="*"
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1609362541
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oath-toolkit
cp %{_builddir}/oath-toolkit-2.6.5/liboath/COPYING %{buildroot}/usr/share/package-licenses/oath-toolkit/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/oath-toolkit-2.6.5/oathtool/COPYING %{buildroot}/usr/share/package-licenses/oath-toolkit/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/oath-toolkit-2.6.5/pam_oath/COPYING %{buildroot}/usr/share/package-licenses/oath-toolkit/8624bcdae55baeef00cd11d5dfcfa60f68710a02
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/oathtool
/usr/bin/pskctool

%files data
%defattr(-,root,root,-)
/usr/share/xml/pskc/catalog-pskc.xml
/usr/share/xml/pskc/pskc-schema.xsd
/usr/share/xml/pskc/xenc-schema.xsd
/usr/share/xml/pskc/xmldsig-core-schema.xsd

%files dev
%defattr(-,root,root,-)
/usr/include/liboath/oath.h
/usr/include/pskc/container.h
/usr/include/pskc/enums.h
/usr/include/pskc/errors.h
/usr/include/pskc/exports.h
/usr/include/pskc/global.h
/usr/include/pskc/keypackage.h
/usr/include/pskc/pskc.h
/usr/include/pskc/version.h
/usr/lib64/liboath.so
/usr/lib64/libpskc.so
/usr/lib64/pkgconfig/liboath.pc
/usr/lib64/pkgconfig/libpskc.pc
/usr/share/man/man3/oath_authenticate_usersfile.3
/usr/share/man/man3/oath_base32_decode.3
/usr/share/man/man3/oath_base32_encode.3
/usr/share/man/man3/oath_bin2hex.3
/usr/share/man/man3/oath_check_version.3
/usr/share/man/man3/oath_done.3
/usr/share/man/man3/oath_hex2bin.3
/usr/share/man/man3/oath_hotp_generate.3
/usr/share/man/man3/oath_hotp_validate.3
/usr/share/man/man3/oath_hotp_validate_callback.3
/usr/share/man/man3/oath_init.3
/usr/share/man/man3/oath_strerror.3
/usr/share/man/man3/oath_strerror_name.3
/usr/share/man/man3/oath_totp_generate.3
/usr/share/man/man3/oath_totp_generate2.3
/usr/share/man/man3/oath_totp_validate.3
/usr/share/man/man3/oath_totp_validate2.3
/usr/share/man/man3/oath_totp_validate2_callback.3
/usr/share/man/man3/oath_totp_validate3.3
/usr/share/man/man3/oath_totp_validate3_callback.3
/usr/share/man/man3/oath_totp_validate4.3
/usr/share/man/man3/oath_totp_validate4_callback.3
/usr/share/man/man3/oath_totp_validate_callback.3
/usr/share/man/man3/pskc_add_keypackage.3
/usr/share/man/man3/pskc_build_xml.3
/usr/share/man/man3/pskc_check_version.3
/usr/share/man/man3/pskc_done.3
/usr/share/man/man3/pskc_free.3
/usr/share/man/man3/pskc_get_cryptomodule_id.3
/usr/share/man/man3/pskc_get_device_devicebinding.3
/usr/share/man/man3/pskc_get_device_expirydate.3
/usr/share/man/man3/pskc_get_device_issueno.3
/usr/share/man/man3/pskc_get_device_manufacturer.3
/usr/share/man/man3/pskc_get_device_model.3
/usr/share/man/man3/pskc_get_device_serialno.3
/usr/share/man/man3/pskc_get_device_startdate.3
/usr/share/man/man3/pskc_get_device_userid.3
/usr/share/man/man3/pskc_get_id.3
/usr/share/man/man3/pskc_get_key_algorithm.3
/usr/share/man/man3/pskc_get_key_algparm_chall_checkdigits.3
/usr/share/man/man3/pskc_get_key_algparm_chall_encoding.3
/usr/share/man/man3/pskc_get_key_algparm_chall_max.3
/usr/share/man/man3/pskc_get_key_algparm_chall_min.3
/usr/share/man/man3/pskc_get_key_algparm_resp_checkdigits.3
/usr/share/man/man3/pskc_get_key_algparm_resp_encoding.3
/usr/share/man/man3/pskc_get_key_algparm_resp_length.3
/usr/share/man/man3/pskc_get_key_algparm_suite.3
/usr/share/man/man3/pskc_get_key_data_b64secret.3
/usr/share/man/man3/pskc_get_key_data_counter.3
/usr/share/man/man3/pskc_get_key_data_secret.3
/usr/share/man/man3/pskc_get_key_data_time.3
/usr/share/man/man3/pskc_get_key_data_timedrift.3
/usr/share/man/man3/pskc_get_key_data_timeinterval.3
/usr/share/man/man3/pskc_get_key_friendlyname.3
/usr/share/man/man3/pskc_get_key_id.3
/usr/share/man/man3/pskc_get_key_issuer.3
/usr/share/man/man3/pskc_get_key_policy_expirydate.3
/usr/share/man/man3/pskc_get_key_policy_keyusages.3
/usr/share/man/man3/pskc_get_key_policy_numberoftransactions.3
/usr/share/man/man3/pskc_get_key_policy_pinencoding.3
/usr/share/man/man3/pskc_get_key_policy_pinkeyid.3
/usr/share/man/man3/pskc_get_key_policy_pinmaxfailedattempts.3
/usr/share/man/man3/pskc_get_key_policy_pinmaxlength.3
/usr/share/man/man3/pskc_get_key_policy_pinminlength.3
/usr/share/man/man3/pskc_get_key_policy_pinusagemode.3
/usr/share/man/man3/pskc_get_key_policy_startdate.3
/usr/share/man/man3/pskc_get_key_profileid.3
/usr/share/man/man3/pskc_get_key_reference.3
/usr/share/man/man3/pskc_get_key_userid.3
/usr/share/man/man3/pskc_get_keypackage.3
/usr/share/man/man3/pskc_get_signed_p.3
/usr/share/man/man3/pskc_get_version.3
/usr/share/man/man3/pskc_global_done.3
/usr/share/man/man3/pskc_global_init.3
/usr/share/man/man3/pskc_global_log.3
/usr/share/man/man3/pskc_init.3
/usr/share/man/man3/pskc_keyusage2str.3
/usr/share/man/man3/pskc_output.3
/usr/share/man/man3/pskc_parse_from_memory.3
/usr/share/man/man3/pskc_pinusagemode2str.3
/usr/share/man/man3/pskc_set_cryptomodule_id.3
/usr/share/man/man3/pskc_set_device_devicebinding.3
/usr/share/man/man3/pskc_set_device_expirydate.3
/usr/share/man/man3/pskc_set_device_issueno.3
/usr/share/man/man3/pskc_set_device_manufacturer.3
/usr/share/man/man3/pskc_set_device_model.3
/usr/share/man/man3/pskc_set_device_serialno.3
/usr/share/man/man3/pskc_set_device_startdate.3
/usr/share/man/man3/pskc_set_device_userid.3
/usr/share/man/man3/pskc_set_id.3
/usr/share/man/man3/pskc_set_key_algorithm.3
/usr/share/man/man3/pskc_set_key_algparm_chall_checkdigits.3
/usr/share/man/man3/pskc_set_key_algparm_chall_encoding.3
/usr/share/man/man3/pskc_set_key_algparm_chall_max.3
/usr/share/man/man3/pskc_set_key_algparm_chall_min.3
/usr/share/man/man3/pskc_set_key_algparm_resp_checkdigits.3
/usr/share/man/man3/pskc_set_key_algparm_resp_encoding.3
/usr/share/man/man3/pskc_set_key_algparm_resp_length.3
/usr/share/man/man3/pskc_set_key_algparm_suite.3
/usr/share/man/man3/pskc_set_key_data_b64secret.3
/usr/share/man/man3/pskc_set_key_data_counter.3
/usr/share/man/man3/pskc_set_key_data_secret.3
/usr/share/man/man3/pskc_set_key_data_time.3
/usr/share/man/man3/pskc_set_key_data_timedrift.3
/usr/share/man/man3/pskc_set_key_data_timeinterval.3
/usr/share/man/man3/pskc_set_key_friendlyname.3
/usr/share/man/man3/pskc_set_key_id.3
/usr/share/man/man3/pskc_set_key_issuer.3
/usr/share/man/man3/pskc_set_key_policy_expirydate.3
/usr/share/man/man3/pskc_set_key_policy_keyusages.3
/usr/share/man/man3/pskc_set_key_policy_numberoftransactions.3
/usr/share/man/man3/pskc_set_key_policy_pinencoding.3
/usr/share/man/man3/pskc_set_key_policy_pinkeyid.3
/usr/share/man/man3/pskc_set_key_policy_pinmaxfailedattempts.3
/usr/share/man/man3/pskc_set_key_policy_pinmaxlength.3
/usr/share/man/man3/pskc_set_key_policy_pinminlength.3
/usr/share/man/man3/pskc_set_key_policy_pinusagemode.3
/usr/share/man/man3/pskc_set_key_policy_startdate.3
/usr/share/man/man3/pskc_set_key_profileid.3
/usr/share/man/man3/pskc_set_key_reference.3
/usr/share/man/man3/pskc_set_key_userid.3
/usr/share/man/man3/pskc_set_version.3
/usr/share/man/man3/pskc_sign_x509.3
/usr/share/man/man3/pskc_str2keyusage.3
/usr/share/man/man3/pskc_str2pinusagemode.3
/usr/share/man/man3/pskc_str2valueformat.3
/usr/share/man/man3/pskc_strerror.3
/usr/share/man/man3/pskc_strerror_name.3
/usr/share/man/man3/pskc_validate.3
/usr/share/man/man3/pskc_valueformat2str.3
/usr/share/man/man3/pskc_verify_x509crt.3

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/liboath/api-index-1-10-0.html
/usr/share/gtk-doc/html/liboath/api-index-1-12-0.html
/usr/share/gtk-doc/html/liboath/api-index-1-4-0.html
/usr/share/gtk-doc/html/liboath/api-index-1-6-0.html
/usr/share/gtk-doc/html/liboath/api-index-1-8-0.html
/usr/share/gtk-doc/html/liboath/api-index-2-4-0.html
/usr/share/gtk-doc/html/liboath/api-index-2-6-0.html
/usr/share/gtk-doc/html/liboath/api-index-full.html
/usr/share/gtk-doc/html/liboath/home.png
/usr/share/gtk-doc/html/liboath/index.html
/usr/share/gtk-doc/html/liboath/intro.html
/usr/share/gtk-doc/html/liboath/left-insensitive.png
/usr/share/gtk-doc/html/liboath/left.png
/usr/share/gtk-doc/html/liboath/liboath-oath.html
/usr/share/gtk-doc/html/liboath/liboath.devhelp2
/usr/share/gtk-doc/html/liboath/right-insensitive.png
/usr/share/gtk-doc/html/liboath/right.png
/usr/share/gtk-doc/html/liboath/style.css
/usr/share/gtk-doc/html/liboath/up-insensitive.png
/usr/share/gtk-doc/html/liboath/up.png
/usr/share/gtk-doc/html/libpskc/api-index-2-2-0.html
/usr/share/gtk-doc/html/libpskc/api-index-full.html
/usr/share/gtk-doc/html/libpskc/ch02s02.html
/usr/share/gtk-doc/html/libpskc/ch02s03.html
/usr/share/gtk-doc/html/libpskc/ch02s04.html
/usr/share/gtk-doc/html/libpskc/home.png
/usr/share/gtk-doc/html/libpskc/index.html
/usr/share/gtk-doc/html/libpskc/left-insensitive.png
/usr/share/gtk-doc/html/libpskc/left.png
/usr/share/gtk-doc/html/libpskc/libpskc-container.html
/usr/share/gtk-doc/html/libpskc/libpskc-enums.html
/usr/share/gtk-doc/html/libpskc/libpskc-errors.html
/usr/share/gtk-doc/html/libpskc/libpskc-global.html
/usr/share/gtk-doc/html/libpskc/libpskc-keypackage.html
/usr/share/gtk-doc/html/libpskc/libpskc-pskc.html
/usr/share/gtk-doc/html/libpskc/libpskc-version.html
/usr/share/gtk-doc/html/libpskc/libpskc.devhelp2
/usr/share/gtk-doc/html/libpskc/pskc-reference.html
/usr/share/gtk-doc/html/libpskc/pskc-tutorial-libpskc-create.html
/usr/share/gtk-doc/html/libpskc/pskc-tutorial-libpskc-sign.html
/usr/share/gtk-doc/html/libpskc/pskc-tutorial-libpskc-verify.html
/usr/share/gtk-doc/html/libpskc/pskc-tutorial-pskctool.html
/usr/share/gtk-doc/html/libpskc/pskc-tutorial-quickstart.html
/usr/share/gtk-doc/html/libpskc/pskc-tutorial.html
/usr/share/gtk-doc/html/libpskc/right-insensitive.png
/usr/share/gtk-doc/html/libpskc/right.png
/usr/share/gtk-doc/html/libpskc/style.css
/usr/share/gtk-doc/html/libpskc/up-insensitive.png
/usr/share/gtk-doc/html/libpskc/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib/security/pam_oath.so
/usr/lib64/liboath.so.0
/usr/lib64/liboath.so.0.1.3
/usr/lib64/libpskc.so.0
/usr/lib64/libpskc.so.0.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oath-toolkit/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/oath-toolkit/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/oathtool.1
/usr/share/man/man1/pskctool.1
