#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : oath-toolkit
Version  : 2.6.1
Release  : 1
URL      : http://download.savannah.nongnu.org/releases/oath-toolkit/oath-toolkit-2.6.1.tar.gz
Source0  : http://download.savannah.nongnu.org/releases/oath-toolkit/oath-toolkit-2.6.1.tar.gz
Summary  : Library for Portable Symmetric Key Container
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+ LGPL-2.1 LGPL-2.1+
Requires: oath-toolkit-bin
Requires: oath-toolkit-lib
Requires: oath-toolkit-doc
BuildRequires : Linux-PAM-dev
BuildRequires : docbook-xml
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(xmlsec1)
BuildRequires : valgrind

%description
The OATH Toolkit makes it easy to build one-time password
authentication systems.  It contains shared libraries, command line
tools and a PAM module.  Supported technologies include the
event-based HOTP algorithm (RFC4226) and the time-based TOTP algorithm
(RFC6238).  OATH stands for Open AuTHentication, which is the
organization that specify the algorithms.  For managing secret key
files, the Portable Symmetric Key Container (PSKC) format described in
RFC6030 is supported.

%package bin
Summary: bin components for the oath-toolkit package.
Group: Binaries

%description bin
bin components for the oath-toolkit package.


%package dev
Summary: dev components for the oath-toolkit package.
Group: Development
Requires: oath-toolkit-lib
Requires: oath-toolkit-bin
Provides: oath-toolkit-devel

%description dev
dev components for the oath-toolkit package.


%package doc
Summary: doc components for the oath-toolkit package.
Group: Documentation

%description doc
doc components for the oath-toolkit package.


%package lib
Summary: lib components for the oath-toolkit package.
Group: Libraries

%description lib
lib components for the oath-toolkit package.


%prep
%setup -q -n oath-toolkit-2.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525995412
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1525995412
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/oathtool

%files dev
%defattr(-,root,root,-)
/usr/include/liboath/oath.h
/usr/lib64/liboath.so
/usr/lib64/pkgconfig/liboath.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
/usr/share/gtk-doc/html/liboath/api-index-1-10-0.html
/usr/share/gtk-doc/html/liboath/api-index-1-12-0.html
/usr/share/gtk-doc/html/liboath/api-index-1-4-0.html
/usr/share/gtk-doc/html/liboath/api-index-1-6-0.html
/usr/share/gtk-doc/html/liboath/api-index-1-8-0.html
/usr/share/gtk-doc/html/liboath/api-index-2-4-0.html
/usr/share/gtk-doc/html/liboath/api-index-2-6-0.html
/usr/share/gtk-doc/html/liboath/api-index-full.html
/usr/share/gtk-doc/html/liboath/home.png
/usr/share/gtk-doc/html/liboath/index.html
/usr/share/gtk-doc/html/liboath/index.sgml
/usr/share/gtk-doc/html/liboath/intro.html
/usr/share/gtk-doc/html/liboath/left-insensitive.png
/usr/share/gtk-doc/html/liboath/left.png
/usr/share/gtk-doc/html/liboath/liboath-oath.html
/usr/share/gtk-doc/html/liboath/liboath.devhelp2
/usr/share/gtk-doc/html/liboath/right-insensitive.png
/usr/share/gtk-doc/html/liboath/right.png
/usr/share/gtk-doc/html/liboath/style.css
/usr/share/gtk-doc/html/liboath/up-insensitive.png
/usr/share/gtk-doc/html/liboath/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib/security/pam_oath.so
/usr/lib64/liboath.so.0
/usr/lib64/liboath.so.0.1.3
